"use client"

import Link from "next/link"
import { LiquidCtaButton } from "@/components/buttons/liquid-cta-button"
import GhostFibers from "@/components/core/GhostFibers"
import { Sparkles, ArrowRight } from "lucide-react"

export function HeroSection() {
  return <section id="company" className="min-h-screen flex flex-col items-center justify-center px-6 pt-24 pb-20 relative overflow-hidden"><div className="absolute inset-x-0 top-0 opacity-70"><div style={{ width: "100%", height: "600px", position: "relative" }}><GhostFibers lineColor="#0d0b14" glowColor="#030304" speed={0.33} scale={2} rotation={7} rotationSpeed={0.33} layers={4} waveAmplitude={0.095} waveFrequency={1.1} waveSpeed={-1.35} layerSpeed={-0.23} twist={0.1} twistFrequency={2.7} twistSpeed={1.2} lineFrequency={1} lineSpacing={2} lineSharpness={8} glowFalloff={16} glowIntensity={0.3} brightness={0.95} blueBoost={0.65} vignette={0.89} grain={0} dpr={1.5} /></div></div><div className="absolute inset-0 bg-gradient-to-b from-zinc-900/35 via-zinc-950/55 to-zinc-950" /><div className="relative z-10 text-center max-w-3xl mx-auto"><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-zinc-900/80 border border-zinc-800 mb-8"><Sparkles className="w-4 h-4 text-zinc-400" /><span className="text-sm text-zinc-400">Education Before Speculation · IV-SOL Ecosystem</span></div><h1 className="font-display text-5xl md:text-7xl font-bold tracking-tight mb-6"><span className="text-zinc-100 block">Digital Finance Education</span><span className="bg-gradient-to-r from-zinc-500 via-zinc-300 to-zinc-500 bg-clip-text text-transparent">for the IV-SOL Era.</span></h1><p className="text-lg md:text-xl text-zinc-500 max-w-2xl mx-auto mb-10 leading-relaxed text-balance">IVT Media Group helps learners understand digital finance, blockchain, AI, cybersecurity, and the IV-SOL ecosystem through practical guidance from Vaulted Academy.</p><div className="flex flex-col sm:flex-row items-center justify-center gap-4"><Link href="#contact"><LiquidCtaButton>Request Access</LiquidCtaButton></Link><Link href="#capabilities" className="group flex items-center gap-2 px-6 py-3 text-sm font-medium text-zinc-400 hover:text-zinc-100 transition-colors"><span>Explore Our Work</span><ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform duration-300" /></Link></div></div></section>
}
